using VehicleDetailsLookup.Shared.Models.Enums;

namespace VehicleDetailsLookup.Models.Database.AiData
{
    /// <summary>
    /// Defines the structure for storing AI-generated vehicle details in the database.
    /// </summary>
    public interface IAiDataDbModel
    {
        /// <summary>
        /// The text content generated by AI for the vehicle.
        /// </summary>
        string? GeneratedText { get; set; }

        /// <summary>
        /// The vehicle's registration number associated with the AI-generated content.
        /// </summary>
        string? RegistrationNumber { get; set; }

        /// <summary>
        /// The category or type of AI-generated vehicle information.
        /// </summary>
        AiType Type { get; set; }

        /// <summary>
        /// The date and time when the AI record was last updated.
        /// </summary>
        DateTime Updated { get; set; }
    }
}