// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleDetailsLookup.Models.Database;

#nullable disable

namespace VehicleDetailsLookup.Migrations
{
    [DbContext(typeof(VehicleDbContext))]
    [Migration("20251227212642_AI_Data_MetaData")]
    partial class AI_Data_MetaData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.AiData.AiDataDbModel", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("GeneratedText")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaData")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationNumber", "Type");

                    b.ToTable("AiData");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Details.DetailsDbModel", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Colour")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfLastV5CIssued")
                        .HasColumnType("TEXT");

                    b.Property<string>("EngineCapacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuelType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Make")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("MonthOfFirstRegistration")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("MotExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("MotStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("TaxDueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearOfManufacture")
                        .HasColumnType("INTEGER");

                    b.HasKey("RegistrationNumber");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Image.ImageDbModel", b =>
                {
                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("RegistrationNumber", "Url");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Lookup.LookupDbModel", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("DateTime", "RegistrationNumber");

                    b.HasIndex("RegistrationNumber");

                    b.ToTable("Lookups");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Mot.MotDefectDbModel", b =>
                {
                    b.Property<string>("TestNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dangerous")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TestNumber", "Description");

                    b.ToTable("MotDefects");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Mot.MotTestDbModel", b =>
                {
                    b.Property<string>("TestNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("OdometerUnit")
                        .HasColumnType("TEXT");

                    b.Property<long>("OdometerValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("TestNumber");

                    b.ToTable("MotTests");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Lookup.LookupDbModel", b =>
                {
                    b.HasOne("VehicleDetailsLookup.Models.Database.Details.DetailsDbModel", "Details")
                        .WithMany("Lookups")
                        .HasForeignKey("RegistrationNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Details");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Mot.MotDefectDbModel", b =>
                {
                    b.HasOne("VehicleDetailsLookup.Models.Database.Mot.MotTestDbModel", "MotTest")
                        .WithMany("MotDefects")
                        .HasForeignKey("TestNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotTest");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Details.DetailsDbModel", b =>
                {
                    b.Navigation("Lookups");
                });

            modelBuilder.Entity("VehicleDetailsLookup.Models.Database.Mot.MotTestDbModel", b =>
                {
                    b.Navigation("MotDefects");
                });
#pragma warning restore 612, 618
        }
    }
}
