using MudBlazor;
using VehicleDetailsLookup.Client.Styling;

namespace VehicleDetailsLookup.Client.Components.Layout
{
    // Defines the MudBlazor light and dark palettes from AppPalette so component Color props
    // and CSS variables stay consistent across the vehicle lookup UI.
    public class Theme
    {
        public static readonly MudTheme theme = new()
        {
            PaletteLight = new PaletteLight()
            {
                Black = AppPalette.Text,
                White = AppPalette.White,
                Primary = AppPalette.Brand,
                PrimaryContrastText = AppPalette.White,
                Secondary = AppPalette.SecondaryText,
                SecondaryContrastText = AppPalette.White,
                Tertiary = AppPalette.Teal,
                TertiaryContrastText = AppPalette.White,
                Info = AppPalette.Brand,
                InfoContrastText = AppPalette.White,
                Success = AppPalette.Success,
                SuccessContrastText = AppPalette.White,
                Warning = AppPalette.Warning,
                WarningContrastText = AppPalette.White,
                Error = AppPalette.Error,
                ErrorContrastText = AppPalette.White,
                Dark = AppPalette.Text,
                DarkContrastText = AppPalette.White,
                TextPrimary = AppPalette.Text,
                TextSecondary = AppPalette.SecondaryText,
                TextDisabled = "rgba(11, 12, 12, 0.38)",
                ActionDefault = AppPalette.SecondaryText,
                ActionDisabled = "rgba(11, 12, 12, 0.26)",
                ActionDisabledBackground = "rgba(11, 12, 12, 0.12)",
                Background = AppPalette.TemplateBackground,
                BackgroundGray = AppPalette.GrayLighter,
                Surface = AppPalette.BodyBackground,
                DrawerBackground = AppPalette.BodyBackground,
                DrawerText = AppPalette.Text,
                DrawerIcon = AppPalette.GrayDefault,
                AppbarBackground = AppPalette.Brand,
                AppbarText = AppPalette.White,
                LinesDefault = AppPalette.Border,
                LinesInputs = AppPalette.Border,
                TableLines = AppPalette.Border,
                TableStriped = "rgba(11, 12, 12, 0.02)",
                TableHover = "rgba(11, 12, 12, 0.04)",
                Divider = AppPalette.Border,
                DividerLight = AppPalette.Text,
                PrimaryDarken = AppPalette.BrandDarken,
                PrimaryLighten = AppPalette.BrandLighten,
                SecondaryDarken = AppPalette.GrayDarker,
                SecondaryLighten = AppPalette.GrayDefault,
                TertiaryDarken = AppPalette.TealDarken,
                TertiaryLighten = AppPalette.TealLighten,
                InfoDarken = AppPalette.BrandDarken,
                InfoLighten = AppPalette.BrandLighten,
                SuccessDarken = AppPalette.SuccessDarken,
                SuccessLighten = AppPalette.SuccessLighten,
                WarningDarken = AppPalette.WarningDarken,
                WarningLighten = AppPalette.WarningLighten,
                ErrorDarken = AppPalette.ErrorDarken,
                ErrorLighten = AppPalette.ErrorLighten,
                DarkDarken = AppPalette.GrayDarker,
                DarkLighten = AppPalette.GrayDark,
                HoverOpacity = 0.06,
                RippleOpacity = 0.1,
                RippleOpacitySecondary = 0.2,
                GrayDefault = AppPalette.GrayDefault,
                GrayLight = AppPalette.GrayLight,
                GrayLighter = AppPalette.GrayLighter,
                GrayDark = AppPalette.GrayDark,
                GrayDarker = AppPalette.GrayDarker,
                OverlayDark = AppPalette.OverlayDark,
                OverlayLight = "rgba(255, 255, 255, 0.5)",
            },
            PaletteDark = new PaletteDark()
            {
                Black = AppPalette.DarkBackground,
                Primary = AppPalette.Brand,
                PrimaryContrastText = AppPalette.White,
                Secondary = AppPalette.DarkTextSecondary,
                SecondaryContrastText = AppPalette.DarkTextPrimary,
                Tertiary = AppPalette.TealLighten,
                TertiaryContrastText = AppPalette.DarkTextPrimary,
                Info = AppPalette.BrandLighten,
                InfoContrastText = AppPalette.DarkTextPrimary,
                Success = AppPalette.SuccessLighten,
                SuccessContrastText = AppPalette.DarkTextPrimary,
                Warning = AppPalette.WarningLighten,
                WarningContrastText = AppPalette.DarkTextPrimary,
                Error = AppPalette.ErrorLighten,
                ErrorContrastText = AppPalette.DarkTextPrimary,
                Dark = AppPalette.DarkBackground,
                DarkContrastText = AppPalette.DarkTextPrimary,
                TextPrimary = AppPalette.DarkTextPrimary,
                TextSecondary = AppPalette.DarkTextSecondary,
                TextDisabled = "rgba(243, 243, 243, 0.38)",
                ActionDefault = AppPalette.DarkTextSecondary,
                ActionDisabled = "rgba(243, 243, 243, 0.26)",
                ActionDisabledBackground = "rgba(243, 243, 243, 0.12)",
                Background = AppPalette.DarkBackground,
                BackgroundGray = AppPalette.DarkBackground,
                Surface = AppPalette.DarkSurface,
                DrawerBackground = AppPalette.DarkBackground,
                DrawerText = AppPalette.DarkTextSecondary,
                DrawerIcon = AppPalette.DarkTextSecondary,
                AppbarBackground = AppPalette.Brand,
                AppbarText = AppPalette.White,
                LinesDefault = "rgba(206, 206, 206, 0.2)",
                LinesInputs = "rgba(206, 206, 206, 0.3)",
                TableLines = "rgba(206, 206, 206, 0.2)",
                TableStriped = "rgba(255, 255, 255, 0.04)",
                TableHover = "rgba(255, 255, 255, 0.06)",
                Divider = "rgba(206, 206, 206, 0.2)",
                DividerLight = "rgba(243, 243, 243, 0.08)",
                PrimaryDarken = AppPalette.BrandDarken,
                PrimaryLighten = AppPalette.BrandLighten,
                InfoDarken = AppPalette.BrandDarken,
                InfoLighten = AppPalette.BrandLighten,
                SuccessDarken = AppPalette.SuccessDarken,
                SuccessLighten = AppPalette.SuccessLighten,
                WarningDarken = AppPalette.WarningDarken,
                WarningLighten = AppPalette.WarningLighten,
                ErrorDarken = AppPalette.ErrorDarken,
                ErrorLighten = AppPalette.ErrorLighten,
                DarkDarken = "#121416",
                DarkLighten = AppPalette.DarkSurface,
                GrayDefault = AppPalette.GrayDefault,
                GrayLight = AppPalette.GrayLight,
                GrayLighter = AppPalette.GrayDark,
                GrayDark = AppPalette.GrayDefault,
                GrayDarker = AppPalette.DarkTextSecondary,
            },
            LayoutProperties = new LayoutProperties()
            {
                DefaultBorderRadius = "4px",
                DrawerMiniWidthLeft = "56px",
                DrawerMiniWidthRight = "56px",
                DrawerWidthLeft = "240px",
                DrawerWidthRight = "240px",
                AppbarHeight = "64px",
            },
            Typography = new Typography()
            {
                Default = new DefaultTypography
                {
                    FontFamily = ["Roboto", "Helvetica", "Arial", "sans-serif"],
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                H1 = new H1Typography
                {
                    FontWeight = "300",
                    FontSize = "6rem",
                    LineHeight = "1.167",
                    LetterSpacing = "-.01562em",
                    TextTransform = "none",
                },
                H2 = new H2Typography
                {
                    FontWeight = "300",
                    FontSize = "3.75rem",
                    LineHeight = "1.2",
                    LetterSpacing = "-.00833em",
                    TextTransform = "none",
                },
                H3 = new H3Typography
                {
                    FontWeight = "400",
                    FontSize = "3rem",
                    LineHeight = "1.167",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H4 = new H4Typography
                {
                    FontWeight = "400",
                    FontSize = "2.125rem",
                    LineHeight = "1.235",
                    LetterSpacing = ".00735em",
                    TextTransform = "none",
                },
                H5 = new H5Typography
                {
                    FontWeight = "400",
                    FontSize = "1.5rem",
                    LineHeight = "1.334",
                    LetterSpacing = "0",
                    TextTransform = "none",
                },
                H6 = new H6Typography
                {
                    FontWeight = "500",
                    FontSize = "1.25rem",
                    LineHeight = "1.6",
                    LetterSpacing = ".0075em",
                    TextTransform = "none",
                },
                Subtitle1 = new Subtitle1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Subtitle2 = new Subtitle2Typography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.57",
                    LetterSpacing = ".00714em",
                    TextTransform = "none",
                },
                Body1 = new Body1Typography
                {
                    FontWeight = "400",
                    FontSize = "1rem",
                    LineHeight = "1.5",
                    LetterSpacing = ".00938em",
                    TextTransform = "none",
                },
                Body2 = new Body2Typography
                {
                    FontWeight = "400",
                    FontSize = ".875rem",
                    LineHeight = "1.43",
                    LetterSpacing = ".01071em",
                    TextTransform = "none",
                },
                Button = new ButtonTypography
                {
                    FontWeight = "500",
                    FontSize = ".875rem",
                    LineHeight = "1.75",
                    LetterSpacing = ".02857em",
                    TextTransform = "none",
                },
                Caption = new CaptionTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "1.66",
                    LetterSpacing = ".03333em",
                    TextTransform = "none",
                },
                Overline = new OverlineTypography
                {
                    FontWeight = "400",
                    FontSize = ".75rem",
                    LineHeight = "2.66",
                    LetterSpacing = ".08333em",
                    TextTransform = "none",
                },
            },
            ZIndex = new ZIndex()
            {
                Drawer = 1100,
                Popover = 1200,
                AppBar = 1300,
                Dialog = 1400,
                Snackbar = 1500,
                Tooltip = 1600,
            },
        };
    }
}
