name: Build and Publish Blazor WebAssembly

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore .NET dependencies
      run: dotnet restore VehicleDetailsLookup.sln

    - name: Build solution
      run: dotnet build VehicleDetailsLookup.sln --configuration Release --no-restore

    - name: Install dotnet-ef as a local tool
      run: dotnet tool install dotnet-ef --version 9.0.0 --tool-path .tools
  
    - name: Add local tool path to PATH
      run: echo "$(pwd)/.tools" >> $GITHUB_PATH
    
    - name: Update database (apply migrations)
      run: dotnet-ef database update --project VehicleDetailsLookup/VehicleDetailsLookup.csproj --startup-project VehicleDetailsLookup/VehicleDetailsLookup.csproj
      env:
        ConnectionStrings__DefaultConnection: ${{ secrets.DEFAULT_CONNECTION_STRING }}
        DOTNET_ROOT: /home/runner/.dotnet

    - name: Run tests
      run: dotnet test VehicleDetailsLookup.sln --no-build --verbosity normal

    - name: Publish Blazor WebAssembly app
      run: dotnet publish VehicleDetailsLookup.Client/VehicleDetailsLookup.Client.csproj --configuration Release --output ./publish

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: blazor-publish
        path: ./publish
